# Generated by Django 6.0.4 on 2026-05-30 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_turnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultorioParticular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('piso_depto', models.CharField(blank=True, max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=25)),
                ('medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultorio_particular', to='gestion_turnos.medico')),
            ],
        ),
    ]
