# Generated by Django 6.0.4 on 2026-05-31 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_turnos', '0002_consultorioparticular'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultorioparticular',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultorios', to='gestion_turnos.ciudad'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='aprobado', max_length=20),
        ),
    ]
