# Generated by Django 6.0.4 on 2026-04-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_turnos', '0003_medico_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquehorario',
            name='duracion_turno',
            field=models.IntegerField(choices=[(30, '30 minutos'), (60, '60 minutos')], default=30),
        ),
    ]
