# Generated by Django 6.0.4 on 2026-04-20 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_turnos', '0004_bloquehorario_duracion_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloquehorario',
            name='activo',
        ),
    ]
