from .medico import Medico
from .paciente import Paciente
from .turno import Turno
from .bloque import BloqueHorario
from .especialidad import Especialidad
from .obra_social  import ObraSocial
from .reserva import Reserva
from .clinica import Clinica
from .ciudad import Ciudad
from .provincia import Provincia
from .consultorio_particular import ConsultorioParticular